### PR TITLE
Adding multiprocessing support, multiple processes will upload images

### PR DESCRIPTION
**Pull request by adisuissa**
Added a --processes_nb command line arguments that creates multiple processes, each with its own engine, that process upload tasks.
Needed to change the Engine's run method to decouple the main execution loop of the engine, from the abort (break) invoked by a user.

### CODE REVIEW

**Comment by dkleissa** [comment]
@adisuissa - We've made a few changes to client.py in our integration branch so i'm expecting merge conflicts. Reviewing now and testing. I'll let you know when we push it to our integration branch and then back to master. Thanks!

**Comment by dkleissa** [comment]
@adisuissa - I pulled your changes into integration and made a few tweaks. Overall it's great, thanks! Can you sign our contributor agreement? I'll push to master and close once you're done.

**Comment by adisuissa** [comment]
@dkleissa I thought I already signed contributor agreement. Not sure if it was for this repo or not, but will check.

**Comment by dkleissa** [comment]
@adisuissa - my bad, just realized since I'm taking part in the PR the auto-check assumed I needed to sign the agreement as well. All good!

**Pull request merged**
